apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
  namespace: demo-app
  labels:
    app: demo-app
type: Opaque
stringData:
  DB_USERNAME: "db_admin_user"
  DB_PASSWORD: "SuperSecretPassword123!"
  API_KEY: "sk_live_9948100592881a2810"
